// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarbergIC_Böteskassa.Data;

namespace WarbergIC_Böteskassa.Migrations
{
    [DbContext(typeof(DbCon))]
    [Migration("20210903112535_initiate")]
    partial class initiate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarbergIC_Böteskassa.Models.Böter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kommentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ÅtaladId")
                        .HasColumnType("int");

                    b.Property<int?>("ÅtalspunktId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ÅtaladId");

                    b.HasIndex("ÅtalspunktId");

                    b.ToTable("Böter");
                });

            modelBuilder.Entity("WarbergIC_Böteskassa.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("WarbergIC_Böteskassa.Models.Regler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pris")
                        .HasColumnType("int");

                    b.Property<string>("Regel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regler");
                });

            modelBuilder.Entity("WarbergIC_Böteskassa.Models.Böter", b =>
                {
                    b.HasOne("WarbergIC_Böteskassa.Models.Person", "Åtalad")
                        .WithMany("Böteslista")
                        .HasForeignKey("ÅtaladId");

                    b.HasOne("WarbergIC_Böteskassa.Models.Regler", "Åtalspunkt")
                        .WithMany()
                        .HasForeignKey("ÅtalspunktId");

                    b.Navigation("Åtalad");

                    b.Navigation("Åtalspunkt");
                });

            modelBuilder.Entity("WarbergIC_Böteskassa.Models.Person", b =>
                {
                    b.Navigation("Böteslista");
                });
#pragma warning restore 612, 618
        }
    }
}
